### ISSUE TITLE
Color and theme fail for tmux and screen

### ISSUE THREAD

**Issue by tprestegard** [afbjorklund/go-termbg#1]
I'm finding that the color and theme detection are failing when using `tmux` or `screen`. For example:

```
# tmux 3.0a
$ go run ./cmd/...
Check terminal background color
  Term : Tmux
  Color: detection failed unknown
  Theme: detection failed unknown
```

```
# GNU Screen 4.08.00
$ go run ./cmd/...
Check terminal background color
  Term : Screen
  Color: detection failed unknown
  Theme: detection failed unknown
```

I don't see any handling for these cases in the [NewRGB](https://github.com/afbjorklund/go-termbg/blob/94dc9311c7a1ed7ada5895f1a13cfd0ca3480277/pkg/termbg/rgb_unix.go#L8) function. I was able to resolve the issue for my configuration (although I don't know if it is a good general solution) by doing this:
```
diff --git a/pkg/termbg/rgb_unix.go b/pkg/termbg/rgb_unix.go
index 0867491..f95c3bf 100644
--- a/pkg/termbg/rgb_unix.go
+++ b/pkg/termbg/rgb_unix.go
@@ -15,7 +15,7 @@ func NewRGB(timeout time.Duration) (RGB, error) {
                return RGB{}, fmt.Errorf("unsupported")
        case RxvtCompatible:
                return fromRxvt()
-       case XtermCompatible:
+       case XtermCompatible, Tmux, Screen:
                return fromXterm(term, timeout)
        default:
                return RGB{}, fmt.Errorf("unknown")
```

**Comment by afbjorklund** [comment]
I actually gave up on this library (termbg), and went over to use https://github.com/muesli/termenv

But can merge a change if you want it, might want to report at https://github.com/dalance/termbg ?

**Comment by tprestegard** [comment]
Oh OK, I'll try that library, I was just playing around with yours today so it's an easy switch. Thanks!
